OrN/rscplus

src/Client/JClassPatcher.java
src/Client/Settings.java

Addresses #9 
Adds config "save_logininfo" in order to either remember or forget your login info. I was unable to figure out how to bypass the "Click here to login" screen without saving the login info.

Added config for saving login info

---

README.md
readme.txt
src/Client/Settings.java
src/Game/Client.java
src/Game/KeyboardHandler.java

- XP and fatigue drops are now toggled via commands or keyboard shortcuts
- The max number of digits shown past the decimal can be changed for fatigue drops (default is 2)
- Fixed a bug where the current fatigue is displayed as a fatigue drop when logging in for the first time during a session
- Updated README to reflect changes

Added configs for XP & fatigue drops

---

src/Game/Client.java
src/Game/XPBar.java

- The XP bar tooltip displays the XP/hr and Actions until level up
- The XP/hr calculation appears after a skill has received 2 XP drops and will continue showing as a tooltip until the skill has not been trained for 3 minutes, after which the XP/hr is reset for that skill
- The Actions until level up calculator uses the average of the XP drops received for that skill recently, not just the last XP drop's value
- Redundant information in the XP bar tooltip has been removed
- The numbers in the XP bar tooltip have been reformatted to be rounded and formatted with commas or the regional standard of the user

XP/Hr + Actions until Level Calculator

---

src/Game/Renderer.java

Trusted compareToIgnoreCase too much when I wrote this, thought the only values that would come out were 10, 0, and -10. Actually lots of values come out, and sometimes it can crash the game when the location offset erroneously overpowers the alphabetic offset.
Hopefully this patch will stop the crash, but it's pretty rare to trigger it. I was able to get it to trigger somewhat reliably when walking north west from the cow pen after killing lots of cows and having a couple of their drops overlap each other then maximum render distance and maximum zoom out and then when you load the cabbage patch and we get about 50 new cabbage items on the ground, and you keep the cow drops in the same frame, the game crashes.
Fixed git history. thanks @thelegendofbrian. Guess I'm supposed to use …

Fix crashing bug with item sorting

---

src/Client/Settings.java
src/Client/Util.java

The world population fetching caused a crash if the client was unable to reach the RuneScape webpage with the world population on it.

Fixed crash on internet disconnect

---

src/Game/Renderer.java

Some rare bug where my item sorting method "violates its general contract" causes the program to crash still. Thought it got fixed, but it still happens. This commit stops the item list from being sorted when there's no reason to, and also wraps the sort function in a generous try catch block. In a worst case scenario, instead of crashing, it should show the item names unsorted for a couple frames now.

Fix crashing bug

---

src/Game/Client.java

Previously, the colored and uncolored PMs wrote slightly different text to the console. They are now consistent with each other.
In the colored console log, usernames with spaces appeared as a `á`:
**Before:**
**After:**

Console log improvement and bugfix

---

src/Client/ConfigWindow.java
src/Client/Settings.java
src/Game/XPBar.java

This is similar to how OSBuddy and RS3 display their XP bars (or should I say XP circles?). This PR doesn't change any default settings; it is still set to default to showing the XP bar left of the settings icon. This way it should not affect any users who do not want this new feature, it only adds extra options for those who prefer it centered.

Added the option to center the position of the XP progress bar.

---

README.md

Nobody seems to use the IRC channel, and when people try to, any messages they post are useless if nobody is online. I made a Discord server that we can use instead. It could be used to better collaborate with developers as well as provide a voice for users.

Replace IRC with Discord

---

README.md
src/Client/ConfigWindow.java
src/Client/JClassPatcher.java
src/Client/Settings.java
src/Game/Bank.java
src/Game/Client.java
src/Game/Help.java
src/Game/Reflection.java

Idea from Pockets, searchable command can be ported graphically in a future update (without much trouble in my opinion). I wanted to have a reset search option without having to speak to the banker but when I tried the Client's class variable values were lost after hooking so I dropped the option.

Searchable bank feature via command and updated help commands

---

src/Client/CacheDownload.java
src/Client/JClassPatcher.java
src/Client/Launcher.java
src/Client/Settings.java
src/Client/Util.java
src/Game/Client.java
src/Game/GameApplet.java
src/Game/Reflection.java

Improves load times drastically after the first run, which is pretty slow (about as slow as before).
@lmsv-mx123 found the grabFile hook method, I just adapted it.
We also handle cache updating in our launcher now, and file grabbing is offloaded onto random world servers (probably will be more efficient, especially if we ever thread this), we only grab the content from the server once now though.

RSC content loader cache

---

src/Client/JClassPatcher.java
src/Client/Settings.java
src/Game/Client.java
src/Game/NPC.java
src/Game/Reflection.java
src/Game/Renderer.java

The display of hits status on other npc/players can be made prettier, if someone wants to pick it up from there. Fixes display overwriting when many combat scenarios are around.

Fix in hits display, adding to npc objs

---

src/Client/Settings.java
src/Game/Client.java
src/Game/Renderer.java

It's tricky to figure out what NPC you're fighting, but I figured out a few tricks to make this almost perfect.
- The NPC and player will have the same bottom Y position when in combat with each other (y coord + height)
- The NPC and player's hitboxes will always (from what I've tested) intersect on the X axis
Using these two criteria, along with the other obvious bits (like having hp info and while the player is actually in combat), this will almost always choose the correct NPC.
It _can_ fail if another player is in combat on top of you and you have your camera rotated a certain way, but when this happens the other monster's info will just be written on top of the one you're actually fighting, so it's not really a big deal, especially for how rare this can happen.

Draw NPC info for what the player is attacking

---

src/Client/Settings.java
src/Game/Renderer.java

Just adds a check for the NPC being on the left of the player. Must've forgotten to add this in the first place.
This should remove tracking NPC's that are on the same level as you but to the right.

Improve combat NPC algorithm

---

README.md
src/Client/ConfigWindow.java
src/Client/JClassPatcher.java
src/Client/Settings.java
src/Game/Client.java
src/Game/Item.java
src/Game/Reflection.java

No longer have to worry on eating or drinking for discontinued rares, quest-only items with drink or eat can get their options swapped.

Edible item fix for discontinued and quest-only

---

src/Client/Launcher.java
src/Client/Settings.java

As of right now, there is no warning for any user that would quickly press no.

Launcher: Show warning when user disables updating

---

src/Client/ConfigWindow.java
src/Client/Settings.java
src/Game/Renderer.java

Simply adds a toggle in the settings for displaying percent of HP remaining when in combat with an NPC opposed to CURRENT_HP/TOTAL_HP

Support percentage toggle in settings

---

src/Client/JClassPatcher.java
src/Game/Client.java
src/Game/Renderer.java

The values are experimental but nonetheless accurate, was getting about 3.1-3.2% for each +1 in prayer equipment status. And the base drain I observed was 1 prayer point per 3.33 seconds.

Adding prayer drain

---

src/Client/JClassPatcher.java
src/Game/Client.java
src/Game/Renderer.java
src/Game/Replay.java

This fixes overlap in retro fps overlay when user is in wild

Fix in retro fps overlay, so it doesnt overlap when user is in wild

---

src/Client/ConfigWindow.java
src/Client/Settings.java
src/Game/Client.java
src/Game/Renderer.java
src/Game/XPBar.java

closes #144 and #152 and addresses an "authenticity bug": The message that RSC+ injects when it sees the phrase "Welcome to RuneScape!" with chattype none can now be turned off. It was that magenta text reminding the user how to open the settings, and also to let you know if there was an update available.

A few bug fixes
