OrN/rscplus

- src/Client/Util.java
- src/Game/Renderer.java
Addresses #2
Fetches the server populations once a minute.
> Added world populations to login screen

- src/Game/Game.java
- src/Game/Renderer.java
I figured if I added the current world to the friends list page, the delay would be too noticeable. Perhaps it could be an overlay on the friends list tab icon?
> Appended current world to window title

- README.md
- src/Game/Client.java
- src/Game/Help.java
Add xmas, rainbow, and system commands with documentation
+*::xmas* - Formats your message in festive Red Green and White colours
+
+*::rainbow* - Formats your message in all the colours of the rainbow (or at least 6)
+
+*::system* - Hides your username and outputs your message
> More chat commands

- src/Client/JClassPatcher.java
- src/Game/Client.java
- src/Game/Reflection.java
- src/Game/Renderer.java
Have included precise world coordinate position (localregion + region) + plane index (0 is ground) for possible location of the user on the world map. Also patching copyright year since its nice of them to keep RSC running.
> Extended coverage of coord info and patching copyright year

- README.md
- src/Client/ConfigWindow.java
- src/Client/JClassPatcher.java
- src/Client/Settings.java
- src/Game/Client.java
- src/Game/Help.java
- src/Game/Reflection.java
This fixes #56 handy sleep for users to what it should be
> Handy sleep and update in version

- src/Client/JClassPatcher.java
- src/Game/Client.java
- src/Game/Reflection.java
Decided that it might be best not to show directly how to create packets so, I fixed the way sleep method is done
> Fix sleep method

- src/Game/Client.java
Just some small improvements to our updater
> Client: Updater improvements

- src/Client/Util.java
- src/Game/Renderer.java
This will show how many days are left until RSC closes on the login screen.
Any other suggestions?
> Renderer: Display days left until RSC is closed

- src/Client/JClassPatcher.java
- src/Game/Client.java
It hooks into closeConnection method when true specified
> Adding hook for disconnect

- src/Client/JClassPatcher.java
- src/Game/Client.java
- src/Game/Replay.java
I set it up as 5 the fps factor but can be later recustomizable
> Adding hook to set newFPS on replay

- src/Client/ConfigWindow.java
- src/Client/JClassPatcher.java
- src/Client/Settings.java
- src/Game/Renderer.java
- src/Game/Replay.java
- src/Game/ReplayServer.java
Fixes frame time slice, that is what is stored and used as variable in the client, and zeroing out login output
> Rsc replay

- src/Client/ConfigWindow.java
- src/Client/Settings.java
- src/Game/Client.java
- src/Game/KeyboardHandler.java
- src/Game/Renderer.java
- src/Game/Replay.java
also I was setting RECORD_KB_MOUSE in two places. oops
> Add "Record Automatically" feature and bug-fix for consume spacebar

- src/Game/Replay.java
- src/Game/ReplayServer.java
I think this fixes a bit in fps when replay and after replay setting back to normal
> Fixes in fps setting in replay and after replay setting back to normal

- src/Client/JClassPatcher.java
- src/Game/Client.java
This solves issue #92 options received from sever after certain actions (speaking to npcs, dropping special items, etc) are sent to console.
> Hooking recieved options, closes #92

- src/Client/JClassPatcher.java
- src/Game/Client.java
- src/Game/Reflection.java
- src/Game/Renderer.java
Automatically goes into play after selection
> Support for autologin when replay

- README.md
- src/Game/Client.java
- src/Game/Renderer.java
recreated to avoid solving merge conflict
> Tell mac users the status of rsc-replay & update README 

- README.md
- src/Client/ConfigWindow.java
- src/Client/JClassPatcher.java
- src/Client/JConfig.java
- src/Client/Settings.java
- src/Client/Util.java
- src/Game/Client.java
- src/Game/Game.java
- src/Game/KeyboardHandler.java
- src/Game/MouseHandler.java
- src/Game/Reflection.java
- src/Game/Renderer.java
- src/Game/Replay.java
- src/Game/ReplayServer.java
Allows us to record server input/output and play them back in the client offline.
Don't need membership or even an account to test RSC+ features via replays, and you don't need the servers to play them back.
> RSC replays

- src/Client/JClassPatcher.java
- src/Game/Client.java
Might be able to expand a bit on 64 or 1 cases i guess or log or something might be able to be added, should be the same really as it was
> Moving logic a bit up to disconnect hook, also hooking into global function for future cases

- src/Client/ConfigWindow.java
- src/Client/JClassPatcher.java
- src/Client/Settings.java
- src/Game/Client.java
- src/Game/Help.java
- src/Game/Reflection.java
- src/Game/Renderer.java
Retro FPS display in the early 2001 era :) and adding last sound effect played to debug
> Incorporate retro fps overlay and adding sound effect to debug

- src/Client/Launcher.java
I don't think this does anything, but it does, then it deletes your config.ini which isn't good. config.ini is now written for the first time somewhere else.
> remove unnecessary code

- src/Client/ConfigWindow.java
- src/Client/NotificationsHandler.java
- src/Client/Settings.java
- src/Game/Renderer.java
SHOW_SEEK_BAR, SHOW_PLAYER_CONTROLS (unimplemented), TRIGGER_ALERTS_REPLAY and add keyboard toggles (using up the last letters in the alphabet for CTRL-[A-Z])
> Add toggles for Replay

- src/Client/JClassPatcher.java
- src/Client/Logger.java
- src/Game/Replay.java
- src/Game/ReplayServer.java
Actual disconnection support for replays that isn't based on guessing if they disconnected.
> Replay v1 - Full Disconnection Support

- src/Client/ConfigWindow.java
- src/Client/Settings.java
- src/Game/Client.java
Since its more accurate to wikify fatigue units because they are int, with the update on heavy+ config they also see units of fatigue received
> Display also fatigue units gained

- src/Client/QueueWindow.java
- src/Client/Settings.java
need to test on Windows, then it's done
> add ability to edit replay folder name in the queue gui window
